# Generated by Django 6.0.5 on 2026-05-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('mood', models.CharField(max_length=50)),
            ],
        ),
    ]
